var filers = [{"candidate_name":"Mary Walston",
 "committee_names":"Elect Mary Walston",
 "filer_id":14904},
 {"candidate_name":"Robert Lee",
 "committee_names":"Friends of Robert Lee",
 "filer_id":14954},
 {"candidate_name":"Ginny Burdick",
 "committee_names":"Friends of Ginny Burdick",
 "filer_id":5434},
 {"candidate_name":"Dave Hunt",
 "committee_names":"Friends of Dave Hunt",
 "filer_id":4247},
 {"candidate_name":"Nathan Hovekamp",
 "committee_names":"Friends of Nathan R. Hovekamp",
 "filer_id":12527},
 {"candidate_name":"Katie Eyre",
 "committee_names":"Friends of Katie Eyre ",
 "filer_id":14349},
 {"candidate_name":"Fred Warner",
 "committee_names":"Win With Warner",
 "filer_id":14562},
 {"candidate_name":"Bruce Starr",
 "committee_names":"Bruce Starr for State Senate Committee",
 "filer_id":2752},
 {"candidate_name":"Jackie Dingfelder",
 "committee_names":"Friends of Jackie Dingfelder",
 "filer_id":4090},
 {"candidate_name":"LeeAnn Larsen",
 "committee_names":"LeeAnn Larsen for School Board",
 "filer_id":13714},
 {"candidate_name":"Richard Devlin",
 "committee_names":"Friends of Richard Devlin",
 "filer_id":1670},
 {"candidate_name":"Tim Freeman",
 "committee_names":"Friends of Tim Freeman",
 "filer_id":11927},
 {"candidate_name":"Tim Freeman",
 "committee_names":"Friends of Tim Freeman",
 "filer_id":11927},
 {"candidate_name":"Tim Freeman",
 "committee_names":"Friends of Tim Freeman",
 "filer_id":11927},
 {"candidate_name":"Jodie Barram",
 "committee_names":"Jodie Barram for Bend City Council",
 "filer_id":13062},
 {"candidate_name":"Shemia Fagan",
 "committee_names":"Committee to Elect Shemia Fagan",
 "filer_id":14993},
 {"candidate_name":"Lee Beyer",
 "committee_names":"Friends of Lee Beyer",
 "filer_id":14049},
 {"candidate_name":"Richard Cunningham",
 "committee_names":"Friends of Rich Cunningham",
 "filer_id":14006},
 {"candidate_name":"Jason Freilinger",
 "committee_names":"Friends of Jason Freilinger",
 "filer_id":14058},
 {"candidate_name":"Janet Carlson",
 "committee_names":"Friends of Janet Carlson",
 "filer_id":6425},
 {"candidate_name":"Tom Hughes",
 "committee_names":"Friends of Tom Hughes",
 "filer_id":14060},
 {"candidate_name":"PAUL HOLVEY",
 "committee_names":"Paul Holvey for State Representative",
 "filer_id":4788},
 {"candidate_name":"Charles Lee",
 "committee_names":"Chuck Lee Campaign Committee",
 "filer_id":5328},
 {"candidate_name":"Nicholas Fish",
 "committee_names":"Nick Fish for City Council",
 "filer_id":5709},
 {"candidate_name":"Chris Garrett",
 "committee_names":"Friends of Chris Garrett",
 "filer_id":12511},
 {"candidate_name":"Tim Josi",
 "committee_names":"Committee to Elect Tim Josi",
 "filer_id":5786},
 {"candidate_name":"Brian Boquist",
 "committee_names":"Boquist Leadership Fund",
 "filer_id":4893},
 {"candidate_name":"Brian Boquist",
 "committee_names":"Boquist Leadership Fund",
 "filer_id":4893},
 {"candidate_name":"Mark Hass",
 "committee_names":"Friends of Mark Hass",
 "filer_id":11487},
 {"candidate_name":"Carolyn Tomei",
 "committee_names":"Carolyn Tomei for State Representative",
 "filer_id":3545},
 {"candidate_name":"Greg Smith",
 "committee_names":"Committee to Re-Elect Greg Smith",
 "filer_id":3420},
 {"candidate_name":"Jenni Tan",
 "committee_names":"Friends of Jenni Tan",
 "filer_id":15736},
 {"candidate_name":"Mark Johnson",
 "committee_names":"Friends of Mark Johnson",
 "filer_id":14277},
 {"candidate_name":"Val Hoyle",
 "committee_names":"Friends of Val Hoyle",
 "filer_id":13967},
 {"candidate_name":"JERRY BAKER",
 "committee_names":"Jerry Baker for Commissioner",
 "filer_id":16133},
 {"candidate_name":"Kali Ladd",
 "committee_names":"Friends of Kali",
 "filer_id":16136},
 {"candidate_name":"Susie Jones",
 "committee_names":"susiejonesformhccboard",
 "filer_id":16132},
 {"candidate_name":"Tim Knapp",
 "committee_names":"Tim Knapp for Mayor",
 "filer_id":13037},
 {"candidate_name":"Huma Pierce",
 "committee_names":"Friends of Huma Pierce",
 "filer_id":16153},
 {"candidate_name":"Terry Fife",
 "committee_names":"Committee to Elect Terry Fife",
 "filer_id":16157},
 {"candidate_name":"Richard Kimball",
 "committee_names":"Rick Kimball for School Board",
 "filer_id":6584},
 {"candidate_name":"Thomas Colett",
 "committee_names":"Thomas Colett for Beaverton School Board",
 "filer_id":16170},
 {"candidate_name":"Pamela Knowles",
 "committee_names":"Pam Knowles for Schools",
 "filer_id":13648},
 {"candidate_name":"Michael Clarke",
 "committee_names":"Michael T. Clarke Campaign",
 "filer_id":16187},
 {"candidate_name":"Tom Koehler",
 "committee_names":"Tom Koehler for School Board",
 "filer_id":16156},
 {"candidate_name":"Kevin Robertson",
 "committee_names":"Kevin Robertson for School Board",
 "filer_id":16208},
 {"candidate_name":"Jaime Rodriguez",
 "committee_names":"Friends of Jaime Rodriguez ",
 "filer_id":16217},
 {"candidate_name":"Susan Greenberg",
 "committee_names":"Susan Greenberg for Beaverton Schools",
 "filer_id":16219},
 {"candidate_name":"Anne Bryan",
 "committee_names":"Committee to Elect Anne Bryan",
 "filer_id":16220},
 {"candidate_name":"Arnie Roblan",
 "committee_names":"Friends of Arnie Roblan",
 "filer_id":4726},
 {"candidate_name":"Regan Sonnen Molatore",
 "committee_names":"Friends of Regan Molatore",
 "filer_id":16227},
 {"candidate_name":"Jerry Jones",
 "committee_names":"Jerry Jones For THPRD",
 "filer_id":16200},
 {"candidate_name":"Donna Tyner",
 "committee_names":"Friends of Donna Tyner",
 "filer_id":16242},
 {"candidate_name":"Sarah Howell",
 "committee_names":"Sarah Howell for School Board",
 "filer_id":16164},
 {"candidate_name":"Greg Cody",
 "committee_names":"Vote Greg Cody",
 "filer_id":16257},
 {"candidate_name":"Michael Richter",
 "committee_names":"Friends of Michael Richter",
 "filer_id":16259},
 {"candidate_name":"Andrew Decker",
 "committee_names":"Friends of Andrew Decker",
 "filer_id":15521},
 {"candidate_name":"Shawn Lindsay",
 "committee_names":"Friends of Shawn Lindsay",
 "filer_id":13866},
 {"candidate_name":"Angela Dilkes Perry",
 "committee_names":"Friends of Angi Dilkes Perry",
 "filer_id":16260},
 {"candidate_name":"Elizabeth Gerot",
 "committee_names":"Committee to Re-elect Beth Gerot",
 "filer_id":16261},
 {"candidate_name":"Steve Thoroughman",
 "committee_names":"Steve Thoroughman for Canby Fire Board",
 "filer_id":16262},
 {"candidate_name":"Janeen Sollman",
 "committee_names":"Friends of Janeen Sollman",
 "filer_id":13654},
 {"candidate_name":"David Matheson",
 "committee_names":"Matheson for Tigard Tualatin Schools",
 "filer_id":16277},
 {"candidate_name":"Martin Gonzalez",
 "committee_names":"Gonzalez for School Board",
 "filer_id":13680},
 {"candidate_name":"Jay Bengel",
 "committee_names":"Jay Bengel for BSD School Board",
 "filer_id":16282},
 {"candidate_name":"Jennifer Williamson",
 "committee_names":"Friends of Jennifer Williamson",
 "filer_id":15145},
 {"candidate_name":"Rebecca Lantz",
 "committee_names":"Rebecca Lantz for Hillsboro School Board",
 "filer_id":16284},
 {"candidate_name":"George Murdock",
 "committee_names":"Committee to Elect George Murdock",
 "filer_id":16144},
 {"candidate_name":"Stephen Fulton",
 "committee_names":"Fulton for Port Commission",
 "filer_id":16285},
 {"candidate_name":"Armand Vial",
 "committee_names":"Friends of Rich Vial",
 "filer_id":16286},
 {"candidate_name":"Benjamin Unger",
 "committee_names":"Ben Unger for Oregon",
 "filer_id":15238},
 {"candidate_name":"Joseph Gallegos",
 "committee_names":"Friends of Joe Gallegos",
 "filer_id":15859},
 {"candidate_name":"Sam Chase",
 "committee_names":"Friends of Sam Chase",
 "filer_id":15293},
 {"candidate_name":"Glenn Miller",
 "committee_names":"Friends of Glenn Miller",
 "filer_id":16305},
 {"candidate_name":"Joe Pishioneri",
 "committee_names":"Friends of Joe Pishioneri",
 "filer_id":15658},
 {"candidate_name":"Michael Reardon",
 "committee_names":"Reardon for Oregon",
 "filer_id":15621},
 {"candidate_name":"Thuy Tran",
 "committee_names":"Friends for Thuy Tran",
 "filer_id":15483},
 {"candidate_name":"Jeff Barker",
 "committee_names":"Friends of Jeff Barker",
 "filer_id":4270},
 {"candidate_name":"Tina Kotek",
 "committee_names":"Friends of Tina Kotek",
 "filer_id":4792},
 {"candidate_name":"Tom Turner",
 "committee_names":"Keep Sheriff Turner",
 "filer_id":15221},
 {"candidate_name":"Linda Degman",
 "committee_names":"Friends of Linda Degman",
 "filer_id":16341},
 {"candidate_name":"James Knapp",
 "committee_names":"Jim Knapp for Clackamas County",
 "filer_id":15635},
 {"candidate_name":"Gayle Strawn",
 "committee_names":"Elect Gayle Strawn",
 "filer_id":16350},
 {"candidate_name":"James Campbell",
 "committee_names":"Friends of Jim Campbell",
 "filer_id":16283},
 {"candidate_name":"Jack Esp",
 "committee_names":"ESP For County Commissioner ",
 "filer_id":16166},
 {"candidate_name":"Jill Halliburton",
 "committee_names":"Committee To Elect Jill Halliburton",
 "filer_id":16229},
 {"candidate_name":"Don Chance",
 "committee_names":"Committee to Elect Don Chance",
 "filer_id":16211},
 {"candidate_name":"Erik Seligman",
 "committee_names":"Friends of Erik Seligman",
 "filer_id":16252},
 {"candidate_name":"Steve Buel",
 "committee_names":"Buel for School Board",
 "filer_id":13728},
 {"candidate_name":"Karen Delaney",
 "committee_names":"Delaney for LOSD",
 "filer_id":16236},
 {"candidate_name":"Sharon Stiles",
 "committee_names":"Committee to re-elect Sharon Stiles LCC Board Zone 1",
 "filer_id":16216},
 {"candidate_name":"Greg Evans",
 "committee_names":"Friends of Greg Evans",
 "filer_id":16168},
 {"candidate_name":"Vivian Scott",
 "committee_names":"Friends of Vivian Scott",
 "filer_id":16274},
 {"candidate_name":"Tobias Read",
 "committee_names":"Friends of Tobias Read",
 "filer_id":5208},
 {"candidate_name":"Matthew Keating",
 "committee_names":"Oregon for Matt Keating",
 "filer_id":16192},
 {"candidate_name":"John Lively",
 "committee_names":"Committee to Elect John Lively for State Representative, Dist. 12",
 "filer_id":15519},
 {"candidate_name":"Dwight Coon",
 "committee_names":"Friends of Dwight Coon",
 "filer_id":14008},
 {"candidate_name":"Keith Steele",
 "committee_names":"Friends of Keith Steele",
 "filer_id":16254},
 {"candidate_name":"Mark Braverman",
 "committee_names":"Braverman4judge.westlinn",
 "filer_id":16438},
 {"candidate_name":"Robert Stacey",
 "committee_names":"Friends of Bob Stacey",
 "filer_id":13836},
 {"candidate_name":"Floyd Prozanski",
 "committee_names":"Friends for Floyd Prozanski",
 "filer_id":1686},
 {"candidate_name":"Jules Bailey",
 "committee_names":"Friends of Jules",
 "filer_id":12498},
 {"candidate_name":"Shirley Craddick",
 "committee_names":"Shirley Craddick for METRO Councilor",
 "filer_id":13893},
 {"candidate_name":"Michael Dembrow",
 "committee_names":"Friends of Michael Dembrow",
 "filer_id":10967},
 {"candidate_name":"Michael Dembrow",
 "committee_names":"Friends of Michael Dembrow",
 "filer_id":10967},
 {"candidate_name":"Michael Dembrow",
 "committee_names":"Friends of Michael Dembrow",
 "filer_id":10967},
 {"candidate_name":"Steve Spinnett",
 "committee_names":"Take Back Damascus",
 "filer_id":14608},
 {"candidate_name":"Lisa Christon",
 "committee_names":"Lisa Christon for 4J School Board",
 "filer_id":16248},
 {"candidate_name":"Nancy Nathanson",
 "committee_names":"Friends of Nancy Nathanson",
 "filer_id":5152},
 {"candidate_name":"Katherine Schacht",
 "committee_names":"Supporters of Katherine Schacht",
 "filer_id":6204},
 {"candidate_name":"Christopher Cochran",
 "committee_names":"Christopher Cochran for State Senate",
 "filer_id":16641},
 {"candidate_name":"Roger Nyquist",
 "committee_names":"Friends of Roger Nyquist",
 "filer_id":10727},
 {"candidate_name":"Bill Kennemer",
 "committee_names":"Friends of Bill Kennemer",
 "filer_id":5885},
 {"candidate_name":"Edward Truax",
 "committee_names":"Committee to Elect Ed Truax",
 "filer_id":12562},
 {"candidate_name":"Martha Schrader",
 "committee_names":"Friends of Martha Schrader",
 "filer_id":5724},
 {"candidate_name":"Bill Bradbury",
 "committee_names":"Friends of Bill Bradbury",
 "filer_id":3571},
 {"candidate_name":"Kitty Piercy",
 "committee_names":"Kitty Piercy for Mayor",
 "filer_id":6031},
 {"candidate_name":"Leslie Lewis",
 "committee_names":"Citizens for Leslie Lewis",
 "filer_id":5726},
 {"candidate_name":"Rod Park",
 "committee_names":"Friends of Rod Park",
 "filer_id":5715},
 {"candidate_name":"Bob Hermann",
 "committee_names":"Bob Hermann for Washington County District Attorney",
 "filer_id":2837},
 {"candidate_name":"Andy Duyck",
 "committee_names":"Friends of Andy Duyck",
 "filer_id":8065},
 {"candidate_name":"R. Butler",
 "committee_names":"Committee to Elect Tom Butler",
 "filer_id":2773},
 {"candidate_name":"Ron Saxton",
 "committee_names":"Friends of Ron Saxton",
 "filer_id":3503},
 {"candidate_name":"Lou Ogden",
 "committee_names":"Vote 4 Lou Ogden",
 "filer_id":7606},
 {"candidate_name":"Bill Morrisette",
 "committee_names":"Morrisette for Senate Committee",
 "filer_id":2748},
 {"candidate_name":"Keith Mays",
 "committee_names":"Friends of Keith Mays",
 "filer_id":10167},
 {"candidate_name":"Ted Wheeler",
 "committee_names":"Friends of Ted Wheeler",
 "filer_id":5591},
 {"candidate_name":"LaVonne Griffin-Valade",
 "committee_names":"Friends of LaVonne Griffin-Valade",
 "filer_id":5584},
 {"candidate_name":"Kate Brown",
 "committee_names":"Kate Brown Committee",
 "filer_id":931},
 {"candidate_name":"Jim Bernard",
 "committee_names":"Friends of Jim Bernard",
 "filer_id":5964},
 {"candidate_name":"Salvador Peralta",
 "committee_names":"Friends of Sal Peralta",
 "filer_id":5127},
 {"candidate_name":"Kathryn Harrington",
 "committee_names":"Harrington For Metro",
 "filer_id":5719},
 {"candidate_name":"Alan Bates",
 "committee_names":"Committee to Elect Dr. Alan Bates",
 "filer_id":3604},
 {"candidate_name":"Dan Saltzman",
 "committee_names":"Friends of Dan Saltzman",
 "filer_id":5718},
 {"candidate_name":"Chris Edwards",
 "committee_names":"Friends of Chris Edwards",
 "filer_id":5158},
 {"candidate_name":"Thomas Balmer",
 "committee_names":"Re-Elect Supreme Court Justice Tom Balmer Committee",
 "filer_id":4193},
 {"candidate_name":"Thomas Balmer",
 "committee_names":"Re-Elect Supreme Court Justice Tom Balmer Committee",
 "filer_id":4193},
 {"candidate_name":"Betty Bode",
 "committee_names":"Friends of Betty Bode",
 "filer_id":7405},
 {"candidate_name":"Faye Stewart",
 "committee_names":"Friends of Faye",
 "filer_id":5588},
 {"candidate_name":"Patti Milne",
 "committee_names":"Patti Milne for State Senate",
 "filer_id":6284},
 {"candidate_name":"David Nelson",
 "committee_names":"Friends of David Nelson",
 "filer_id":2367},
 {"candidate_name":"Deborah Boone",
 "committee_names":"Boone for State Representative",
 "filer_id":4846},
 {"candidate_name":"Wayne Krieger",
 "committee_names":"Wayne Krieger for State Representative",
 "filer_id":3477},
 {"candidate_name":"john lindsey",
 "committee_names":"The Lindsey Fund",
 "filer_id":6945},
 {"candidate_name":"Bruce Cuff",
 "committee_names":"Friends of Bruce Cuff",
 "filer_id":12758},
 {"candidate_name":"Bruce Cuff",
 "committee_names":"Friends of Bruce Cuff",
 "filer_id":12758},
 {"candidate_name":"Mike Ainsworth",
 "committee_names":"Mike Ainsworth for Polk County Commissioner",
 "filer_id":14324},
 {"candidate_name":"Daniel Jaffer",
 "committee_names":"Committee to Elect Danny Jaffer",
 "filer_id":14342},
 {"candidate_name":"Michael Spasaro",
 "committee_names":"Friends of Michael P. Spasaro",
 "filer_id":12937},
 {"candidate_name":"Lisa Shaw-Ryan",
 "committee_names":"Friends of Lisa",
 "filer_id":14597},
 {"candidate_name":"Jerry Rust",
 "committee_names":"Rust for Commissioner",
 "filer_id":14161},
 {"candidate_name":"Kyle Palmer",
 "committee_names":"Palmer4Silverton",
 "filer_id":14705},
 {"candidate_name":"Debra Birkby",
 "committee_names":"Debra Birkby for Clatsop's South County Commissioner",
 "filer_id":14363},
 {"candidate_name":"Daniel Staton",
 "committee_names":"Retain Dan Staton for Multnomah County Sheriff",
 "filer_id":13980},
 {"candidate_name":"Anthony DeBone",
 "committee_names":"Citizens for Tony DeBone",
 "filer_id":14183},
 {"candidate_name":"Cliff Bentz",
 "committee_names":"Cliff Bentz for State Representative Committee",
 "filer_id":11508},
 {"candidate_name":"Melody Thompson",
 "committee_names":"Committee to elect Melody Thompson",
 "filer_id":14285},
 {"candidate_name":"Sherrie Sprenger",
 "committee_names":"Friends of Sherrie Sprenger",
 "filer_id":12916},
 {"candidate_name":"Jay Bozievich",
 "committee_names":"Friends of Jay Bozievich",
 "filer_id":13965},
 {"candidate_name":"Peter Buckley",
 "committee_names":"Committee to Re-Elect Peter Buckley",
 "filer_id":4824},
 {"candidate_name":"Laurie Monnes Anderson",
 "committee_names":"Friends of Laurie Monnes Anderson",
 "filer_id":3584},
 {"candidate_name":"Sal Esquivel",
 "committee_names":"Committee to Elect Sal Esquivel",
 "filer_id":4813},
 {"candidate_name":"Douglas Whitsett",
 "committee_names":"Committee to Elect Doug Whitsett",
 "filer_id":4821},
 {"candidate_name":"Douglas Whitsett",
 "committee_names":"Committee to Elect Doug Whitsett",
 "filer_id":4821},
 {"candidate_name":"Betty Taylor",
 "committee_names":"Taylor for City Council",
 "filer_id":15249},
 {"candidate_name":"John Huffman",
 "committee_names":"Committee to Elect John E. Huffman",
 "filer_id":11708},
 {"candidate_name":"John Huffman",
 "committee_names":"Committee to Elect John E. Huffman",
 "filer_id":11708},
 {"candidate_name":"Chris Telfer",
 "committee_names":"Committee to Elect Chris Telfer",
 "filer_id":11767},
 {"candidate_name":"Vic Gilliam",
 "committee_names":"Friends of Vic Gilliam",
 "filer_id":5690},
 {"candidate_name":"Catherine McKeown",
 "committee_names":"Caddy McKeown for Representative",
 "filer_id":15298},
 {"candidate_name":"Gail Whitsett",
 "committee_names":"Gail Whitsett for Oregon",
 "filer_id":15319},
 {"candidate_name":"Gail Whitsett",
 "committee_names":"Gail Whitsett for Oregon",
 "filer_id":15319},
 {"candidate_name":"Warren Bednarz",
 "committee_names":"Warren Bednarz for Salem City Council",
 "filer_id":15297},
 {"candidate_name":"Bruce Altizer",
 "committee_names":"Committee to Elect Bruce Altizer",
 "filer_id":15327},
 {"candidate_name":"Diane Rosenbaum",
 "committee_names":"Rosenbaum for Senate (Diane)",
 "filer_id":1430},
 {"candidate_name":"Rob Handy",
 "committee_names":"Re-Elect Rob Handy County Commissioner",
 "filer_id":12525},
 {"candidate_name":"Dick Schouten",
 "committee_names":"Neighbors for Schouten",
 "filer_id":10067},
 {"candidate_name":"Brent Barton",
 "committee_names":"Friends of Brent Barton",
 "filer_id":12493},
 {"candidate_name":"Dan Clem",
 "committee_names":"Dan Clem for Polk County",
 "filer_id":14131},
 {"candidate_name":"Alex Gardner",
 "committee_names":"Alex Gardner for DA",
 "filer_id":10767},
 {"candidate_name":"Scott Rose",
 "committee_names":"Rose For Mayor",
 "filer_id":15419},
 {"candidate_name":"Bill Dant",
 "committee_names":"Bill Dant For Mayor Committee",
 "filer_id":15466},
 {"candidate_name":"Bradley Witt",
 "committee_names":"Brad Witt for State Representative",
 "filer_id":5079},
 {"candidate_name":"Aaron Felton",
 "committee_names":"Felton For District Attorney",
 "filer_id":15529},
 {"candidate_name":"Keith Heck",
 "committee_names":"Heck Yes for Commissioner",
 "filer_id":15623},
 {"candidate_name":"Colleen Roberts",
 "committee_names":"Colleen Roberts for County Commissioner",
 "filer_id":15683},
 {"candidate_name":"Christopher Humphreys",
 "committee_names":"Chris Humphreys for Sheriff",
 "filer_id":15711},
 {"candidate_name":"Earl Fisher",
 "committee_names":"Committee to Elect Earl Fisher",
 "filer_id":8386},
 {"candidate_name":"Linda Simmons",
 "committee_names":"Simmons For Commissioner",
 "filer_id":15775},
 {"candidate_name":"Christopher Gorsek",
 "committee_names":"Friends of Chris Gorsek",
 "filer_id":14515},
 {"candidate_name":"Douglas Daoust",
 "committee_names":"Doug Daoust for Troutdale Mayor",
 "filer_id":15843},
 {"candidate_name":"Manuel Castaneda",
 "committee_names":"Friends of Manuel Castaneda",
 "filer_id":15248},
 {"candidate_name":"Gene Whisnant",
 "committee_names":"Committee to Elect Gene Whisnant",
 "filer_id":4653},
 {"candidate_name":"John Nelsen",
 "committee_names":"Friends of John Nelsen",
 "filer_id":12536},
 {"candidate_name":"Fred Girod",
 "committee_names":"Friends of Fred Girod",
 "filer_id":5458},
 {"candidate_name":"Sid Leiken",
 "committee_names":"Sid Leiken for County Commissioner",
 "filer_id":12786},
 {"candidate_name":"Jeremy Ferguson",
 "committee_names":"Friends of Jeremy Ferguson",
 "filer_id":13688},
 {"candidate_name":"Rick Dyer",
 "committee_names":"The Committee To Elect Rick Dyer",
 "filer_id":13807},
 {"candidate_name":"W. Rod Monroe",
 "committee_names":"Friends of Rod Monroe",
 "filer_id":5319},
 {"candidate_name":"Brad Avakian",
 "committee_names":"Committee to Elect Brad Avakian",
 "filer_id":4152},
 {"candidate_name":"Kim Thatcher",
 "committee_names":"Friends of Kim Thatcher",
 "filer_id":4871},
 {"candidate_name":"Brian Clem",
 "committee_names":"Oregonians for Clem",
 "filer_id":5133},
 {"candidate_name":"Mary Nolan",
 "committee_names":"Mary Nolan for City Council",
 "filer_id":3701},
 {"candidate_name":"Peter Courtney",
 "committee_names":"Peter Courtney for State Senate",
 "filer_id":470},
 {"candidate_name":"Lawrence George",
 "committee_names":"Larry George for State Senate",
 "filer_id":5107},
 {"candidate_name":"Carl Hosticka",
 "committee_names":"Friends of Carl Hosticka",
 "filer_id":12614},
 {"candidate_name":"Daniel Holladay",
 "committee_names":"Friends of Daniel Holladay",
 "filer_id":14407},
 {"candidate_name":"Cherryl  Walker",
 "committee_names":"Cherryl Walker for BCC3",
 "filer_id":15516},
 {"candidate_name":"Vicki Berger",
 "committee_names":"Friends of Vicki Berger",
 "filer_id":4112},
 {"candidate_name":"Timothy Bishop",
 "committee_names":"Committee to Elect Tim Bishop Coos County Commissioner Position #2",
 "filer_id":15547},
 {"candidate_name":"Julie Parrish",
 "committee_names":"Friends of Julie Parrish",
 "filer_id":14592},
 {"candidate_name":"James \"Jim\" Egan",
 "committee_names":"Committee to Elect Judge James C. Egan",
 "filer_id":15637},
 {"candidate_name":"Vance Day",
 "committee_names":"The Committee to Elect Judge Vance Day",
 "filer_id":15604},
 {"candidate_name":"Craig Pope",
 "committee_names":"Friends of Craig Pope",
 "filer_id":14242},
 {"candidate_name":"Ted Ferrioli",
 "committee_names":"Friends of Ted Ferrioli",
 "filer_id":3215},
 {"candidate_name":"Ron Le Blanc",
 "committee_names":"Friends of Ron Le Blanc",
 "filer_id":15744},
 {"candidate_name":"David Orr",
 "committee_names":"Justice Without Politics",
 "filer_id":15841},
 {"candidate_name":"Monica Keenan",
 "committee_names":"Friends of Monica Keenan",
 "filer_id":15886}]
