var test_data = [{"tran_id":1669996,
 "original_id":1669996,
 "tran_date":"2014-02-06",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"The Leadership Fund (26190)",
 "sub_type":"Cash Expenditure",
 "amount":25,
 "aggregate_amount":0,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-03",
 "review_by_name":null,
 "review_date":null,
 "due_date":"2014-03-10",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-10",
 "addr_book_agent_name":null,
 "book_type":null,
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":null,
 "addr_line2":null,
 "city":null,
 "state":null,
 "zip":null,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'100':4 'cash':2 'expenditur':3 'miscellan':1",
 "purp_desc_vectors":"",
 "all_vectors":"'100':10 'bruce':1 'cash':8 'committe':6 'expenditur':9 'miscellan':7 'senat':5 'starr':2 'state':4"},
 {"tran_id":1663864,
 "original_id":1663864,
 "tran_date":"2014-02-04",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"The Leadership Fund (2690)",
 "sub_type":"In-Kind Contribution",
 "amount":110.72,
 "aggregate_amount":110.72,
 "contributor_payee_committee_id":2690,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-10",
 "review_by_name":"lydplu",
 "review_date":"2014-03-13",
 "due_date":"2014-02-06",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":"Caucus photos",
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-10",
 "addr_book_agent_name":null,
 "book_type":"Political Committee",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"89358 Cranberry Lane",
 "addr_line2":null,
 "city":"Bandon",
 "state":"OR",
 "zip":97411,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":"General Operational Expenses (need description)",
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'2690':4 'fund':3 'leadership':2",
 "purp_desc_vectors":"'caucus':1 'photo':2",
 "all_vectors":"'2690':10 'bruce':1 'caucus':11 'committe':6 'fund':9 'leadership':8 'photo':12 'senat':5 'starr':2 'state':4"},
 {"tran_id":1663866,
 "original_id":1663866,
 "tran_date":"2014-02-03",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Oregon Beverage Recycling Cooperative",
 "sub_type":"In-Kind Contribution",
 "amount":186.7,
 "aggregate_amount":186.7,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-10",
 "review_by_name":"lydplu",
 "review_date":"2014-03-13",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":"Fundraising event expenses",
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-10",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"PO Box 4468",
 "addr_line2":null,
 "city":"Portland",
 "state":"OR",
 "zip":97208,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":"Fundraising Event Expenses",
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'beverag':2 'cooper':4 'oregon':1 'recycl':3",
 "purp_desc_vectors":"'event':2 'expens':3 'fundrais':1",
 "all_vectors":"'beverag':8 'bruce':1 'committe':6 'cooper':10 'event':12 'expens':13 'fundrais':11 'oregon':7 'recycl':9 'senat':5 'starr':2 'state':4"},
 {"tran_id":1650576,
 "original_id":1650576,
 "tran_date":"2014-01-31",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Broadway Cab, LLC",
 "sub_type":"Cash Contribution",
 "amount":250,
 "aggregate_amount":250,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-02-03",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"8725 NE Emerson St",
 "addr_line2":null,
 "city":"Portland",
 "state":"OR",
 "zip":97220,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'broadway':1 'cab':2 'llc':3",
 "purp_desc_vectors":"",
 "all_vectors":"'broadway':7 'bruce':1 'cab':8 'committe':6 'llc':9 'senat':5 'starr':2 'state':4"},
 {"tran_id":1650577,
 "original_id":1650577,
 "tran_date":"2014-01-31",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Windsor Rock Products3",
 "sub_type":"Cash Contribution",
 "amount":500,
 "aggregate_amount":500,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-02-03",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"PO Box 7322",
 "addr_line2":null,
 "city":"Salem",
 "state":"OR",
 "zip":97303,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'product':3 'rock':2 'windsor':1",
 "purp_desc_vectors":"",
 "all_vectors":"'bruce':1 'committe':6 'product':9 'rock':8 'senat':5 'starr':2 'state':4 'windsor':7"},
 {"tran_id":1650578,
 "original_id":1650578,
 "tran_date":"2014-01-31",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Coalition for a Healthy Oregon (4749)",
 "sub_type":"Cash Contribution",
 "amount":1000,
 "aggregate_amount":1000,
 "contributor_payee_committee_id":4749,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-02-03",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Political Committee",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"825 NE Multnomah",
 "addr_line2":"Suite 300",
 "city":"Portland",
 "state":"OR",
 "zip":97232,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'4749':6 'coalit':1 'healthi':4 'oregon':5",
 "purp_desc_vectors":"",
 "all_vectors":"'4749':12 'bruce':1 'coalit':7 'committe':6 'healthi':10 'oregon':11 'senat':5 'starr':2 'state':4"},
 {"tran_id":1650579,
 "original_id":1650579,
 "tran_date":"2014-01-31",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Northwest Grocery Assoc. PAC (152)",
 "sub_type":"Cash Contribution",
 "amount":500,
 "aggregate_amount":500,
 "contributor_payee_committee_id":152,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-02-03",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Political Committee",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"8565 SW Salish Ln Ste 100",
 "addr_line2":null,
 "city":"Wilsonville",
 "state":"OR",
 "zip":97070,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'152':5 'assoc':3 'groceri':2 'northwest':1 'pac':4",
 "purp_desc_vectors":"",
 "all_vectors":"'152':11 'assoc':9 'bruce':1 'committe':6 'groceri':8 'northwest':7 'pac':10 'senat':5 'starr':2 'state':4"},
 {"tran_id":1664114,
 "original_id":1664114,
 "tran_date":"2014-01-31",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Miscellaneous Cash Expenditures $100 and under25",
 "sub_type":"Cash Expenditure",
 "amount":12,
 "aggregate_amount":0,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-03",
 "review_by_name":null,
 "review_date":null,
 "due_date":"2014-03-03",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-03",
 "addr_book_agent_name":null,
 "book_type":null,
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":null,
 "addr_line2":null,
 "city":null,
 "state":null,
 "zip":null,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'100':4 'cash':2 'expenditur':3 'miscellan':1",
 "purp_desc_vectors":"",
 "all_vectors":"'100':10 'bruce':1 'cash':8 'committe':6 'expenditur':9 'miscellan':7 'senat':5 'starr':2 'state':4"},
 {"tran_id":1663882,
 "original_id":1663882,
 "tran_date":"2014-01-30",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Datajockeys, LLC",
 "sub_type":"Cash Expenditure",
 "amount":120,
 "aggregate_amount":120,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-03",
 "review_by_name":"jenher",
 "review_date":"2014-03-10",
 "due_date":"2014-03-03",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":"annual web account",
 "intrst_rate":null,
 "check_nbr":"2709.0",
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-03",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"PO Box 2093",
 "addr_line2":null,
 "city":"Hillsboro",
 "state":"OR",
 "zip":97123,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":"General Operational Expenses (need description)",
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'datajockey':1 'llc':2",
 "purp_desc_vectors":"'account':3 'annual':1 'web':2",
 "all_vectors":"'account':11 'annual':9 'bruce':1 'committe':6 'datajockey':7 'llc':8 'senat':5 'starr':2 'state':4 'web':10"},
 {"tran_id":1664113,
 "original_id":1664113,
 "tran_date":"2014-01-30",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Miscellaneous Cash Expenditures $100 and under2",
 "sub_type":"Cash Expenditure",
 "amount":10,
 "aggregate_amount":0,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-03-03",
 "review_by_name":null,
 "review_date":null,
 "due_date":"2014-03-03",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-03-03",
 "addr_book_agent_name":null,
 "book_type":null,
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":null,
 "addr_line2":null,
 "city":null,
 "state":null,
 "zip":null,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'100':4 'cash':2 'expenditur':3 'miscellan':1",
 "purp_desc_vectors":"",
 "all_vectors":"'100':10 'bruce':1 'cash':8 'committe':6 'expenditur':9 'miscellan':7 'senat':5 'starr':2 'state':4"},
 {"tran_id":1645516,
 "original_id":1645516,
 "tran_date":"2014-01-29",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Baker Rock Resources1231",
 "sub_type":"Cash Contribution",
 "amount":10000,
 "aggregate_amount":1000,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-01-29",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"21880 SW Farmington Rd",
 "addr_line2":null,
 "city":"Beaverton",
 "state":"OR",
 "zip":97007,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'baker':1 'resourc':3 'rock':2",
 "purp_desc_vectors":"",
 "all_vectors":"'baker':7 'bruce':1 'committe':6 'resourc':9 'rock':8 'senat':5 'starr':2 'state':4"},
 {"tran_id":1645516,
 "original_id":1645516,
 "tran_date":"2014-01-29",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Baker Rock Resources2123",
 "sub_type":"Cash Contribution",
 "amount":5000,
 "aggregate_amount":1000,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-01-29",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"21880 SW Farmington Rd",
 "addr_line2":null,
 "city":"Beaverton",
 "state":"OR",
 "zip":97007,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'baker':1 'resourc':3 'rock':2",
 "purp_desc_vectors":"",
 "all_vectors":"'baker':7 'bruce':1 'committe':6 'resourc':9 'rock':8 'senat':5 'starr':2 'state':4"},
 {"tran_id":1645516,
 "original_id":1645516,
 "tran_date":"2014-01-29",
 "tran_status":"Original",
 "filer":"Bruce Starr for State Senate Committee",
 "contributor_payee":"Baker Resources123 332",
 "sub_type":"Cash Contribution",
 "amount":1000,
 "aggregate_amount":1000,
 "contributor_payee_committee_id":null,
 "filer_id":2752,
 "attest_by_name":"Nancy E Stout",
 "attest_date":"2014-01-29",
 "review_by_name":"jenher",
 "review_date":"2014-02-19",
 "due_date":"2014-02-05",
 "occptn_ltr_date":null,
 "pymt_sched_txt":null,
 "purp_desc":null,
 "intrst_rate":null,
 "check_nbr":null,
 "tran_stsfd_ind":false,
 "filed_by_name":"Nancy E Stout",
 "filed_date":"2014-02-05",
 "addr_book_agent_name":null,
 "book_type":"Business Entity",
 "title_txt":null,
 "occptn_txt":null,
 "emp_name":null,
 "emp_city":null,
 "emp_state":null,
 "employ_ind":false,
 "self_employ_ind":false,
 "addr_line1":"21880 SW Farmington Rd",
 "addr_line2":null,
 "city":"Beaverton",
 "state":"OR",
 "zip":97007,
 "zip_plus_four":null,
 "county":null,
 "purpose_codes":null,
 "exp_date":null,
 "last_updated":null,
 "filer_vectors":"'bruce':1 'committe':6 'senat':5 'starr':2 'state':4",
 "contributor_payee_vectors":"'baker':1 'resourc':3 'rock':2",
 "purp_desc_vectors":"",
 "all_vectors":"'baker':7 'bruce':1 'committe':6 'resourc':9 'rock':8 'senat':5 'starr':2 'state':4"}]
